config/routes.rb
Rails.application.routes.draw do
 
 resources :movies do
  	#collection é para coleçao de filmes, não quer saber qual é.
  	#Posso ter dois tipos de rota, movie1/edit ou movie/search
  	collection do 
  		get 'search'
  	end
  end

  root 'store#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
	has_and_belongs_to_many :movies

	def to_s
		self.name
		#pega voce mesmo com self e retorna o nome
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
	has_and_belongs_to_many :movies

	def to_s
		self.name
	end
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_and_belongs_to_many :actors
	has_and_belongs_to_many :directors

	def self.search(query)
		self.where('title LIKE ?', "%#{query}%").order('id DESC')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    def search
      @movies =  Movie.search(params[:query])
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :runtime, :genre, :plot, :language, :country, :awards, :poster_url, :imdb_id, :imdb_rating)
    end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@movies = Movie.all.sample 21
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="collapse bg-inverse" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 py-4">
            <h4 class="text-white">Sobre a Movie Store</h4>
            <p class="text-muted">Nós insistimos em vender filmes.</p>
          </div>
          <div class="col-sm-4 py-4">
            <h4 class="text-white">Opções</h4>
            <ul class="list-unstyled">
              <li><a href="#" class="text-white">Menu 1</a></li>
              <li><a href="#" class="text-white">Menu 2</a></li>
              <li><a href="#" class="text-white">Menu 3</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-inverse bg-inverse">
      <div class="container d-flex justify-content-between">
        <%= link_to "Movie Store", root_path, class: "navbar-brand" %>
        <%= form_tag(search_movies_path, method: :get) do %>
          <%= text_field_tag :query, params[:query], placeholder: "Busque por títulos", class: "form-control" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>

      <%= yield %>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Movie Store é uma aplicação exemplo utilizada durante o <a href="http://cursorails.kutzke.com.br">curso de Ruby on Rails</a></p>
      </div>
    </footer>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="field">
    <%= f.label :runtime %>
    <%= f.text_field :runtime %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :plot %>
    <%= f.text_area :plot %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :awards %>
    <%= f.text_field :awards %>
  </div>

  <div class="field">
    <%= f.label :poster_url %>
    <%= f.text_field :poster_url %>
  </div>

  <div class="field">
    <%= f.label :imdb_id %>
    <%= f.text_field :imdb_id %>
  </div>

  <div class="field">
    <%= f.label :imdb_rating %>
    <%= f.text_field :imdb_rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="card">
  <img class="card-img-top" src="<%= movie.poster_url %>" width="100%" alt="<%= movie.title %>">
  <div class="card-block">
    <h4 class="card-title">
      <%= movie.title %>
    </h4>
    <h6><small>IMDB Rating: <%= movie.imdb_rating %></small></h6>
    <dl class="card-text">
      <dt><%= "Director".pluralize(movie.directors.count) %></dt><dd><%= movie.directors.join ", " %></dd>
      <dt>Actors</dt><dd><%= movie.actors.join ", " %></dd>
      <dt>Plot</dt><dd class="text-justify"><small><%= truncate(movie.plot, length: 200) %></small></dd>
    </dl>
  </div>
  <div class="card-footer">
    <div class="text-center">
      <%= link_to 'More', movie_path(movie), class: "btn btn-primary bt-small" %>
    </div>
  </div>
</div>

app/views/movies/_movies.html.erb
<div class="row">
  <div class="card-columns">
    <%= render @movies %>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Runtime</th>
      <th>Genre</th>
      <th>Plot</th>
      <th>Language</th>
      <th>Country</th>
      <th>Awards</th>
      <th>Poster url</th>
      <th>Imdb</th>
      <th>Imdb rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td><%= movie.runtime %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.plot %></td>
        <td><%= movie.language %></td>
        <td><%= movie.country %></td>
        <td><%= movie.awards %></td>
        <td><%= movie.poster_url %></td>
        <td><%= movie.imdb_id %></td>
        <td><%= movie.imdb_rating %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<div class="container">
  <h2><%= @movies.count %> filme(s) encontrado(s):</h2>

  <%= render "movies/movies" %> 
</div>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @movie.runtime %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Plot:</strong>
  <%= @movie.plot %>
</p>

<p>
  <strong>Language:</strong>
  <%= @movie.language %>
</p>

<p>
  <strong>Country:</strong>
  <%= @movie.country %>
</p>

<p>
  <strong>Awards:</strong>
  <%= @movie.awards %>
</p>

<p>
  <strong>Poster url:</strong>
  <%= @movie.poster_url %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @movie.imdb_id %>
</p>

<p>
  <strong>Imdb rating:</strong>
  <%= @movie.imdb_rating %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/store/index.html.erb
<% unless notice.nil? %>
  <div id="notice" class="alert alert-info"><%= notice %></div>
<% end %>


<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Compre os melhores filmes!</h1>
    <p class="lead text-muted">Porque sua internet será limitada um dia!</p>
    <p>
      <a href="#" class="btn btn-primary">Faça seu acadastro</a>
      <a href="#" class="btn btn-secondary">Já sou usuário</a>
    </p>
  </div>
</section>


<div class="container">
  <h2>Alguns dos nossos melhores filmes ...</h2>

  <%= render "movies/movies" %>
</div>